apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: user11
  labels:
    app: book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: 879772956301.dkr.ecr.ap-southeast-1.amazonaws.com/user11-book:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: api.museum.url
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: api.museum.url
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: v1
kind: Service
metadata:
  name: book
  namespace: user11
  labels:
    app: book
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: book